# Generated by Django 2.2.24 on 2021-07-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='para',
            field=models.TextField(max_length=1000),
        ),
    ]
